name: Cypress Tests

on: [push]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    # enable for running in cypress cloud
    # strategy:
    #   fail-fast: false
    #   matrix:
    #     containers: [1, 2, 3, 4, 5, 6, 7, 8]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: npm install --force

      - name: Injecting secrets
        run: |
          REPLACEMENT1=${{ secrets.CYD_TEST_WALLET_ADDRESS }}
          REPLACEMENT2=${{ secrets.CYD_TEST_WALLET_PRIVATE_KEY }}
          sed -i "s/'CYD_TEST_WALLET_ADDRESS'/'$REPLACEMENT1'/g" ./test/web3MockOnSdk.js
          sed -i "s/'CYD_TEST_WALLET_PRIVATE_KEY'/'$REPLACEMENT2'/g" ./test/web3MockOnSdk.js

      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v5
        with:
          build: npm run esbuild-browser
          start: |
            npx http-server -p 8080 -c-1 --silent
            sleep 5
          browser: chrome

        # enable the following for running in cypress cloud
          # record: true
          # parallel: true
        # env:
        #   CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}



