name: Cypress Tests

on: [push]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        containers: [1, 2, 3, 4, 5]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: npm install --force


      # - name: Checkout all files present
      #   run : |
      #     ls
      #     ls ./dist
      #     ls ./dist/esbuild

      #     print_directory_contents() {
      #       local dir="$1"
      #       local indent="${2:-}"

      #       # Print current directory name
      #       echo "${indent}Directory: $dir"

      #       # Iterate over files and subdirectories in the current directory
      #       for item in "$dir"/*; do
      #           if [ -d "$item" ]; then
      #               # Recursive call for subdirectories
      #               print_directory_contents "$item" "${indent}  "
      #           elif [ -f "$item" ]; then
      #               # Print file name
      #               echo "${indent}  File: $item"
      #           fi
      #       done
      #     }

      #     target_directory="./dist/esbuild"

      #     print_directory_contents "$target_directory"
      - name: Injecting secrets
        run: |
          REPLACEMENT1=${{ secrets.CYD_TEST_WALLET_ADDRESS }}
          REPLACEMENT2=${{ secrets.CYD_TEST_WALLET_PRIVATE_KEY }}
          sed -i "s/'CYD_TEST_WALLET_ADDRESS'/'$REPLACEMENT1'/g" ./test/web3MockOnSdk.js
          sed -i "s/'CYD_TEST_WALLET_PRIVATE_KEY'/'$REPLACEMENT2'/g" ./test/web3MockOnSdk.js

      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v5
        with:
          build: npm run esbuild-browser
          start: |
            npx http-server -p 8080 -c-1 --silent
            sleep 5
          browser: chrome
          record: true
          parallel: true
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}



